version: '3.3'

services:

  db:
    image: mariadb:latest              # Para Raspberry 32 bits cambiar "mariadb:latest" por "yobasystems/alpine-mariadb:latest"
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /srv/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - MYSQL_PASSWORD=xxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:28.0.9
    #image: nextcloud:28.0.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
    volumes:
      - /srv/nextcloud/config:/var/www/html/config
      - /srv/nextcloud/data:/var/www/html/data
      - /srv/nextcloud/custom_apps:/var/www/html/custom_apps
      - /srv/nextcloud/themes:/var/www/html/themes
    environment:
      - MYSQL_PASSWORD=xxxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
